spring:
  application:
    name: microservice-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: microservice-user
          uri: lb://microservice-user
          predicates:
            - Path=/api/auth/**,/api/users/**
        - id: microservice-transactions
          uri: lb://microservice-transactions
          predicates:
            - Path=/api/balance/**,/api/exchangerbalance/**,/api/rates/**,/api/transactions/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka